import type { Metadata } from "next";
import "../globals.css";
import AuthProvider from '@/context/authProvider'
import NavBar from "@/components/public/NavBar";
import { ThemeProvider } from "@/context/themProvider";

export const metadata: Metadata = {
  title: "Feathery",
  description: "Generated by Feathery",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <AuthProvider>
        <ThemeProvider>
      <body>
        <NavBar/>
        {children}
        </body>
        </ThemeProvider>
      </AuthProvider>
    </html>
  );
}
