import type { Metadata } from "next";
import "../globals.css";
import AuthProvider from '@/context/authProvider'
import NavBar from "@/components/message/NavBar";
import SidBar from "@/components/message/SidBar";
import SendMessage from "@/components/message/send-message";

export const metadata: Metadata = {
  title: "Feathery",
  description: "Generated by Feathery",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <AuthProvider>
        
      <body>
        {/* <NavBar/> */}
        <div className="flex">
        <SidBar/>
        <div className="bg-black w-full">
          <NavBar/>
        {children}
        {/* <SendMessage/> */}
        </div>
        
        </div>
        </body>
      </AuthProvider>
    </html>
  );
}
