import MobileNav from "@/components/nav/MobilNav";
import Footer from "@/components/public/footer";
import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/context/authProvider";
import { ThemeProvider } from "@/context/themProvider";
import type { Metadata } from "next";
import "../globals.css";
import "./layout.css";
import NavBar from "@/components/nav/edit-nav";
import SidBar from "@/components/SidBar";
export const metadata: Metadata = {
  title: "Feathery",
  description: "Generated by Feathery",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <AuthProvider>
        <ThemeProvider>
          <body className="">
            <NavBar />

            <SidBar />
            <div className="ml-8">
              {children}
              <Footer />
            </div>
            

            
            <MobileNav />

            <Toaster />
          </body>
        </ThemeProvider>
      </AuthProvider>
    </html>
  );
}
