import type { Metadata } from "next";
import "../globals.css";
import AuthProvider from '@/context/authProvider'

import  NavBar from "@/components/edit-profile/Profile_Edit_Nav";

export const metadata: Metadata = {
  title: "Feathery",
  description: "Generated by Feathery",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        
      <body>
        {/* <NavBar/> */}
     
        <NavBar/>
        {children}
      
        
        </body>
      </AuthProvider>
    </html>
  );
}
